(impl-trait 'SPAXYA5XS51713FDTQ8H94EJ4V579CXMTRNBZKSF.token-a.token-trait)
(define-public (get-balance (account principal))  
  (ok u0))
(define-public (transfer? (from principal) (to principal) (amount uint))  
  (ok u0))